config/routes.rb
Rails.application.routes.draw do
  # Routes for Articles
  get "articles/index", to: "articles#index", as: "index_articles"
  get "articles/search", to: "articles#search", as: "search_articles"
  get "articles/list", to: "articles#list", as: "list_articles"
  get "articles/new", to: "articles#new", as: "new_article"
  post "articles/create", to: "articles#create", as: "create_article"
  patch "articles/update/:id", to: "articles#update", as: "update_article"
  get "articles/show/:id", to: "articles#show", as: "show_article"
  get "articles/edit/:id", to: "articles#edit", as: "edit_article"
  delete "articles/delete/:id", to: "articles#destroy", as: "delete_article"

  # Routes for comments under a specific article
  post "articles/:article_id/comments", to: "comments#create", as: "article_comments"
  delete "articles/:article_id/comments/:id", to: "comments#destroy", as: "delete_comment"

  # Routes for Categories
  get "categories/list", to: "categories#list", as: "list_categories"
  get "categories/new", to: "categories#new", as: "new_category"
  post "categories/create", to: "categories#create", as: "create_category"
  patch "categories/update/:id", to: "categories#update", as: "update_category"
  get "categories/show/:id", to: "categories#show", as: "show_category"
  get "categories/show_delete/:id", to: "categories#show_delete", as: "show_delete_category"
  delete "categories/delete/:id", to: "categories#destroy", as: "delete_category"

  # Routes for Admins
  get "admins/index", to: "admins#index", as: "index_admins"
  patch "admins/hide_unhide/:id", to: "articles#hide_unhide", as: "hide_unhide"
  get "admins/show_delete/:id", to: "articles#show_delete", as: "show_delete"
  get "admins/hidden", to: "articles#show_hidden", as: "hidden_articles"
  get "admins/index/:id", to: "admins#index", as: "index_admins_id"
  get "admins/register", to: "admins#register_form", as: "show_register"
  post "admins/register", to: "admins#register", as: "register"
  get "admins/login", to: "admins#login_form", as: "show_login"
  post "admins/login", to: "admins#login", as: "login"
  delete "logout", to: "admins#logout", as: "logout"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # Default root
  root "articles#index"

end

app/views/admins/index.html.erb
<!------------ Admin Home page for admins ------------>
<!-- If any updates to the articles, display a message to notify the admin-->
<% if flash[:article_notice] %>
  <p class="text-success fw-bold"><%= flash[:article_notice] %></p>
<% end %>
<!-- Display a welcome message with the username -->
<h6>Welcome, <%= @admin.username %>!</h6>
<div class="d-flex justify-content-between align-items-center">
  <!-- Select the heading to display based on the show_hidden flag -->
  <h2 class="mb-0"><%= @show_hidden ? "Hidden Articles" : "Visible Articles" %></h2>
  <!-- New Article button linked to new article form -->
  <%= link_to "Add New Article", new_article_path, type: "button", class: "btn btn-outline-primary" %>
</div>

<!--If there are no articles in the @article array , display a message -->
<% if @articles.blank? %>
  <p>No News found.</p>
<!--If there are any articles, list their title, published date and part of the content -->
<% else %>
  <!-- Display the article list-->
  <ul style="list-style: none; padding: 0; margin: 30px 0 0;" id="categories">
    <!-- Loop through each article in the @articles array -->
    <% @articles.each do |article| %>
      <!-- horizontal line -->
      <hr/>
      <li class="mb-3">
        <div class="d-flex justify-content-between align-items-center">
          <!-- Display the article title as a clickable link to the individual article page -->
          <h5><%= link_to article.title, show_article_path(:id => article.id), style: "text-decoration: none;" %></h5>
          <div class="btn-group btn-group-sm" role="group" aria-label="Edit Article">
            <!-- Edit button linked to edit article form -->
            <%= link_to "Edit", edit_article_path(:id => article.id), type: "button", class: "btn btn-primary" %>
            <!-- Hide/Unhide button to perform either hide or unhide action depending on the is_hidden flag -->
            <%= button_to article.is_hidden ? "Unhide" : "Hide", article.is_hidden ? hide_unhide_path(article.id) : hide_unhide_path(article.id), method: :patch, class: "btn btn-secondary btn-sm rounded-0" %>
            <!-- Delete button linked to show delete view (individual article page) -->
            <%= link_to "Delete", show_delete_path(:id => article.id), method: :get, class: "btn btn-danger" %>
          </div>
        </div>
        <!-- Date the article was created in an appropriate format -->
        <p><%= article.created_at.strftime("%B %d, %Y %H:%M") %></p>
        <p class="mb-4">
          <!-- First 200 words of the article's content -->
          <%= truncate(article.content, length: 200) %>
          <!-- "Read more" link to the individual article page -->
          <%= link_to " Read more >>", show_article_path(:id => article.id), style: "text-decoration: none;" %>
        </p>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/admins/login.html.erb
<!------------ Login page for admins ------------>
<!-- if login fails, display an error message-->
<% if flash[:alert] %>
  <p class="text-danger fw-bold"><%= flash[:alert] %></p>
<% end %>
<!-- Page title -->
<h2>Login</h2>
<!-- horizontal line -->
<hr/>
<!-- Login form -->
<%= form_with url: login_path, method: :post, class: "row g-3" do %>
  <div class="col-md-6">
    <!-- Username field -->
    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= label_tag :username, "Username", class: "form-label" %>
        <%= text_field_tag :username, params[:username], class: "form-control", placeholder: "Enter email", required: true %>
      </div>
    </div>
    <!-- Password field -->
    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= label_tag :password, "Password", class: "form-label" %>
        <%= password_field_tag :password, params[:password], class: "form-control", placeholder: "Enter password", required: true %>
      </div>
    </div>
    <!-- Submit button -->
    <div class="col-sm-10">
      <%= submit_tag "Login", class: "btn btn-primary" %>
    </div>
    <!-- Link to register page -->
    <p class="mt-3">
      <%= link_to "Don't have an account?", show_register_path, style: "text-decoration: none;" %>
    </p>
  </div>
<% end %>

app/views/admins/register.html.erb
<!------------ Register page for new admins ------------>
<!-- if registration fails, display an error message-->
<% if flash[:alert] %>
  <p class="text-danger fw-bold"><%= flash[:alert] %></p>
<% end %>
<!-- Page title -->
<h2>Register</h2>
<!-- horizontal line -->
<hr/>
<!-- Register form -->
<%= form_with model: @admin, url: register_path, method: :post, class: "row g-3" do |f| %>
  <div class="col-md-6">
    <!-- Username field -->
    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.label :username, class: "col-form-label" %>
        <%= f.text_field :username, class: "form-control", placeholder: "Enter username", required: true %>
      </div>
    </div>
    <!-- Password field -->
    <div class="mb-3 row">
      <div class="col-sm-10">
        <%= f.label :password, class: "col-form-label" %>
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password", required: true %>
      </div>
    </div>
    <!-- Password confirmation field -->
    <div class="mb-5 row">
      <div class="col-sm-10">
        <%= f.label :password_confirmation, class: "col-form-label" %>
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password", required: true %>
      </div>
    </div>
    <!-- Submit button -->
    <div class="col-sm-10">
      <%= f.submit "Register", class: "btn btn-primary" %>
    </div>
    <!-- Link to login page -->
    <p class="mt-3">
      <%= link_to "Already have an account?", show_login_path, style: "text-decoration: none;" %>
    </p>
  </div>
<% end %>