config/routes.rb
Rails.application.routes.draw do
  # Routes for Articles
  get "articles/index", to: "articles#index", as: "index_articles"
  get "articles/search", to: "articles#search", as: "search_articles"
  get "articles/list", to: "articles#list", as: "list_articles"
  get "articles/new", to: "articles#new", as: "new_article"
  post "articles/create", to: "articles#create", as: "create_article"
  patch "articles/update/:id", to: "articles#update", as: "update_article"
  get "articles/show/:id", to: "articles#show", as: "show_article"
  get "articles/edit/:id", to: "articles#edit", as: "edit_article"
  delete "articles/delete/:id", to: "articles#destroy", as: "delete_article"

  # Routes for comments under a specific article
  post "articles/:article_id/comments", to: "comments#create", as: "article_comments"
  delete "articles/:article_id/comments/:id", to: "comments#destroy", as: "delete_comment"

  # Routes for Categories
  get "categories/list", to: "categories#list", as: "list_categories"
  get "categories/new", to: "categories#new", as: "new_category"
  post "categories/create", to: "categories#create", as: "create_category"
  patch "categories/update/:id", to: "categories#update", as: "update_category"
  get "categories/show/:id", to: "categories#show", as: "show_category"
  get "categories/show_delete/:id", to: "categories#show_delete", as: "show_delete_category"
  delete "categories/delete/:id", to: "categories#destroy", as: "delete_category"

  # Routes for Admins
  get "admins/index", to: "admins#index", as: "index_admins"
  patch "admins/hide_unhide/:id", to: "articles#hide_unhide", as: "hide_unhide"
  get "admins/show_delete/:id", to: "articles#show_delete", as: "show_delete"
  get "admins/hidden", to: "articles#show_hidden", as: "hidden_articles"
  get "admins/index/:id", to: "admins#index", as: "index_admins_id"
  get "admins/register", to: "admins#register_form", as: "show_register"
  post "admins/register", to: "admins#register", as: "register"
  get "admins/login", to: "admins#login_form", as: "show_login"
  post "admins/login", to: "admins#login", as: "login"
  delete "logout", to: "admins#logout", as: "logout"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # Default root
  root "articles#index"

end

app/models/article.rb
class Article < ApplicationRecord
  # Set up the relationship with Category model
  belongs_to :category
  # Set up the relationship with Comment model and sort them by created date
  # Delete associated comments when an article is deleted
  has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy

  # These declarations enable a good bit of automatic behaviour. E.g., if you have an instance variable @article containing an article, you can retrieve all the comments belonging to that article as an array using @article.comments.
  validates :title, presence: true
  validates :source, presence: true
  validates :content, presence: true, length: { minimum: 10 }

  # Define scope for search * ->() is a lambda function, which takes one or more arguments to perform some logic
  # When Article.search(params[:search]) is called, the value of params[:search] is passed as keyword to the scope
  scope :search, ->(keyword) { where("LOWER(content) LIKE ?", "%#{keyword.downcase}%") }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # Public ---------------------------------------------------------------------

  # List 4 of the latest news articles (Home page/list.html.erb)
  def index
    # Retrieve 4 of the recent, visible articles from the database sorted by the created date
    @articles = Article.where(is_hidden: false).order(created_at: :desc).limit(4)
  end

  # List all news (News page/list.html.erb)
  def list
    # Retrieve all categories in alphabetical order for the headings
    @categories = Category.order(name: :asc)
  end

  # Search function for search bar (Nav/header component)
  def search
    # Check if any keywords have been entered in the search bar
    if params[:search]
      # Filter articles by content
      @articles = Article.where(is_hidden: false).search(params[:search]).order(created_at: :desc)
    else
      # If no search keywords are provided, set @articles to empty
      @articles = []
    end
    render :index
  end

  # Show an individual article page (show.html.erb)
  def show
    # Retrieve an article selected by the user based on the ID passed in the params
    @article = Article.find(params[:id])
  end

  # Admin Tasks ------------------------------------------------------------
  # Show new article form (new.html.erb)
  def new
    # Initialise a new Article object with default values (Visibility: public, Published date: today)
    @article = Article.new(is_hidden: false, created_at: Time.current)
    # Retrieve all categories for the dropdown
    @categories = Category.order(name: :asc)
    render :form
  end

  # Create a new article and save it to the database
  def create
    # Initialise a new article with the parameters submitted via the form (using strong parameters)
    @article = Article.new(article_params)
    # Try to save the article and check if it was successful
    if @article.save
      # Redirect the user to the admin home (index.html.erb)
      redirect_to index_admins_path
      # Store a success message to be displayed on the admin home page
      flash[:article_notice] = "Article saved successfully!"
    else
      # If saving fails, retrieve the categories again for the dropdown in the form
      @categories = Category.all
      # Re-render the new article form
      render :new
      # Store an error message to be displayed above the new article form
      flash.now[:alert] = "Article not saved. #{@article.errors.full_messages.to_sentence}"
    end
  end

  # Edit an existing article
  def edit
    # Find the article to edit by its ID
    @article = Article.find(params[:id])
    # Retrieve all categories to display in the dropdown for category selection
    @categories = Category.all
    render :form
  end

  # Update an existing article
  def update
    # Find the article to update by its ID
    @article = Article.find(params[:id])
    # Check if the article is successfully updated
    if @article.update(article_params)
      # Redirect the user to the individual article page (show.html.erb)
      redirect_to show_article_path(@article)
      # Store a success message to be displayed on the article page
      flash[:update_notice] = "Article updated successfully!"
    else
      # If updating fails, retrieve the categories again for the dropdown in the form
      @categories = Category.all
      # Re-render the edit form
      render :edit
      # Store an error message to be displayed above the edit form
      flash[:update_alert] = "Article not updated. #{@article.errors.full_messages.to_sentence}"
    end
  end

  # Hide or unhide the selected article
  def hide_unhide
    # Find the article by its ID
    @article = Article.find(params[:id])
    # Check the current visibility setting of the article
    if @article.is_hidden
      # If the article is currently hidden, set is_hidden to false (change the visibility to Public)
      @article.update(is_hidden: false)
      # Redirect the user to the hidden articles page (index.html.erb)
      redirect_to hidden_articles_path
      # Store a success message to be displayed on the page
      flash[:article_notice]= "Article visibility updated successfully!"
    else
      # If the article is currently visible, set is_hidden to true (change the visibility to Admin Only)
      @article.update(is_hidden: true)
      # Redirect the user to the visible articles page (index.html.erb)
      redirect_to index_admins_path
      # Store a success message to be displayed on the page
      flash[:article_notice]= "Article visibility updated successfully!"
    end
  end

  # Show all hidden articles
  def show_hidden
    # Find the admin based on the session user_id
    @admin = Admin.find(session[:admin_id]) if session[:admin_id]
    # Fetch all hidden articles
    @articles = Article.where(is_hidden: true).order(created_at: :desc)
    # Set show_hidden to true so the admin index can display the hidden articles
    @show_hidden = true
    # Render the admin index view
    render index_admins_path
  end

  # Show the warning message for the article deletion with the article details
  def show_delete
    # Retrieve an article based on the ID passed in the params
    @article = Article.find(params[:id])
    # Set a show_delete flag to true so that the articles/show page can display the warning message
    @show_delete = true
    # Render the articles/show page (show.html.erb)
    render :show
  end

  # Delete an article from the database
  def destroy
    # Find the article by its ID
    @article = Article.find(params[:id])
    # Delete the found article from the database
    @article.destroy
    # Redirect the user to the admin home page (index.html.erb)
    redirect_to index_admins_path
    # Store a success message to be displayed on the page
    flash[:article_notice]= "Article deleted successfully!"
  end

  # Reusable component ---------------------------------------------------------------------
  private # Restrict access to the following method for security
  # Strong parameters for security
  def article_params
    # Allow users to submit only the specified parameters through the form
    params.require(:article).permit(:title, :content, :category_id, :source, :created_at, :is_hidden)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/form.html.erb
<!------------ New/Edit Article form for admins ------------>
<!-- Check if a new record is created and display the appropriate heading based on the result -->
<h2><%= @article.new_record? ? "Add new article" : "Edit article" %></h2>
<hr/>
<!-- determine the route and request type by checking if the new record is created -->
<%= form_with(model: @article, url: @article.new_record? ? create_article_path : update_article_path(@article), method: @article.new_record? ? :post : :patch, local: true) do |f| %>
  <!-- Title field -->
  <div class="mb-3">
    <%= f.label :title, "Title", class: "col-form-label" %>
    <%= f.text_field :title, class: "form-control", placeholder: "Enter Title", required: true %>
  </div>
  <!-- Category field -->
  <div class="mb-3">
    <%= f.label :category_id, "Category", class: "col-form-label" %>
    <%= f.collection_select :category_id, @categories, :id, :name, { prompt: "Select category" }, class: "form-control", required: true %>
  </div>
  <!-- Source field -->
  <div class="mb-3">
    <%= f.label :source, "Source", class: "col-form-label" %>
    <%= f.text_field :source, class: "form-control", placeholder: "Enter Source", required: true %>
  </div>
  <!-- Published Date field -->
  <div class="mb-3">
    <%= f.label :created_at, "Published Date", class: "col-form-label" %>
    <%= f.datetime_local_field :created_at, value: @article.created_at.strftime("%Y-%m-%dT%H:%M"), class: "form-control", required: true %>

  </div>
  <!-- Visibility Radio Buttons -->
  <div class="mb-3">
    <label class="col-form-label">Visibility</label>
    <div class="form-check">
      <%= f.radio_button :is_hidden, false, id: "flexRadioDefault1", class: "form-check-input" %>
      <%= f.label :is_hidden, "Public", for: "flexRadioDefault1", class: "form-check-label" %>
    </div>
    <div class="form-check">
      <%= f.radio_button :is_hidden, true, id: "flexRadioDefault2", class: "form-check-input" %>
      <%= f.label :is_hidden, "Admin Only", for: "flexRadioDefault2", class: "form-check-label" %>
    </div>
  </div>
  <!-- Content field -->
  <div class="mb-3">
    <%= f.label :content, "Content", class: "col-form-label" %>
    <%= f.text_area :content, class: "form-control", rows: 4, placeholder: "Enter Article Content (More than 10 letters)", required: true %>
  </div>
  <!-- Submit button -->
  <div class="mb-3">
    <%= f.submit @article.new_record? ? "Create New Article" : "Update Article", class: "btn btn-primary align-self-start" %>
  </div>
<% end %>

<!-- If the data is not saved, display an error message -->
<div class="mb-3">
  <% if flash[:alert] %>
    <p class="text-danger fw-bold"><%= flash[:alert] %></p>
  <% end %>
</div>

<!-- Link to the previous page -->
<div><%= link_to "<< Back", index_admins_path, style: "text-decoration: none;" %></div>

app/views/articles/index.html.erb
<!------------ Home page for all users ------------>
<% if params[:search] %>
  <h2>Search Results based on "<%= params[:search] %>"</h2>
<% end %>
<!-- If there are no articles in the @articles array, display a message -->
<% if @articles.blank? %>
  <p>No articles found.</p>
<!-- If there are articles, display the recent news -->
<% else %>
  <!-- if search was not performed, display the heading for the Home page (Recent news) -->
  <h2><%= "Recent News" if params[:search].blank? %></h2>
  <!-- Display the article list-->
  <ul style="list-style: none; padding: 0; margin: 0;" id="articles">
    <!-- Loop through each article in the @articles array -->
    <% @articles.each do |article| %>
      <li>
        <!-- horizontal line -->
        <hr/>
        <!-- Display the article title as a clickable link to the individual article page -->
        <h5><%= link_to article.title, show_article_path(:id => article.id), style: "text-decoration: none;" %></h5>
        <!-- Date the article was created in an appropriate format -->
        <p><%= article.created_at.strftime("%B %d, %Y %H:%M") %></p>
        <p>
          <!-- First 200 words of the article's content -->
          <%= truncate(article.content, length: 200) %>
          <!-- "Read more" link to the individual article page -->
          <%= link_to " Read more >>", show_article_path(:id => article.id),style: "text-decoration: none;" %>
        </p>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/articles/list.html.erb
<!------------ News Page for all users ------------>
<!-- If there are no categories in the @categories array, display a message -->
<% if @categories.blank? %>
  <p>No News found.</p>
<!-- If there are categories, display them and associated news -->
<% else %>
  <!-- Display the category name -->
  <ul style="list-style: none; padding: 0; margin: 30px 0 0;" id="categories">
    <!-- Loop through each category in the @categories array -->
    <% @categories.each do |category| %>
      <li class="mb-5">
        <!-- Display the category name as a clickable link to the individual category page -->
        <h2><%= link_to category.name, show_category_path(category.id), style: "text-decoration: none; color: black;" %></h2>
        <!-- If there are no articles in the category, display a message -->
        <% if category.articles.blank? %>
          <!-- horizontal line -->
          <hr/>
          <!-- message -->
          <p>No articles found in this category.</p>
        <!-- If there are any articles in the category, display their title, date and part of the content -->
        <% else %>
          <!-- Loop through each article in the articles array within each category -->
          <% category.articles.each do |article| %>
            <hr/>
            <!-- Display the article title as a clickable link to the individual article page -->
            <h5><%= link_to article.title, show_article_path(:id => article.id), style: "text-decoration: none;" %></h5>
            <!-- Date the article was created in an appropriate format -->
            <p><%= article.created_at.strftime("%B %d, %Y %H:%M") %><br/></p>
            <p class="mb-4">
              <!-- First 200 words of the article's content -->
              <%= truncate(article.content, length: 200) %>
              <!-- "Read more" link to the individual article page -->
              <%= link_to " Read more >>", show_article_path(:id => article.id), style: "text-decoration: none;" %>
            </p>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/articles/show.html.erb
<!------------ Individual Article Page for all users ------------>
<!-- If show_delete is true, display a warning message and delete/cancel buttons -->
<% if @show_delete %>
  <div class="border border-dark p-3 mb-5">
    <!-- Warning -->
    <h2>Article Title: <%= @article.title %></h2>
    <h5>Are you sure you want to delete this article?</h5>
    <p class="mb-3">This action cannot be undone.</p>
    <!-- Buttons -->
    <div class="d-flex justify-content-start">
      <!-- button to go back to the previous page -->
      <%= button_to "Cancel", index_admins_path, method: :get, class: "btn btn-success" %>
      <!-- button to delete the category -->
      <%= button_to "Delete", delete_article_path(:id => @article.id), method: :delete, class: "btn btn-danger ms-3" %>
    </div>
  </div>
<% end %>

<!-- Article Section -->
<div>
  <!-- If the article was just updated by admin, display a success/error message -->
  <% if flash[:update_notice] %>
    <p class="text-success fw-bold"><%= flash[:update_notice] %></p>
  <% elsif flash[:update_alert] %>
    <p class="text-danger fw-bold"><%= flash[:update_alert] %></p>
  <% end %>
  <!-- Display the article title -->
  <h2 class="mb-3"><%= @article.title %></h2>
  <p class="mb-3">
    <!-- Category name -->
    <strong>Category: </strong> <%= @article.category.name %><br/>
    <!-- Source -->
    <strong>Source: </strong> <%= @article.source %><br/>
    <!-- Created date -->
    <strong>Date:</strong> <%= @article.created_at.strftime(" %B %d, %Y %H:%M") %><br/>
  </p>
  <!-- Content -->
  <p><%= @article.content %></p>
</div>

<!-- Horizontal line -->
<hr/>

<!-- Display all comments for the article -->
<div class="mb-5">
  <!-- If the comment was just created or deleted by admin, display a success/error message -->
  <% if flash[:comment_notice] %>
    <p class="text-success fw-bold"><%= flash[:comment_notice] %></p>
  <% elsif flash[:comment_alert] %>
    <p class="text-danger fw-bold"><%= flash[:comment_alert] %></p>
  <% end %>
  <!-- Comment Section -->
  <h5 class="mb-3">Comments</h5>
  <!-- Loop through each comment associated with the article and display the comment date and body -->
  <% @article.comments.each do |comment| %>
    <div class="d-flex justify-content-start">
      <p class="d-flex align-items-center mb-2.5">
        <!-- Created date -->
        <strong class="me-3"><%= comment.created_at.strftime("%B %d, %Y %H:%M") %>:</strong>
        <!-- Comment body -->
        <%= comment.body %>
      </p>
      <!-- Delete button for comments and Simple alert to be displayed when the admin is trying to delete a comment-->
      <% if session[:admin_id] %>
        <div class="ms-3">
          <!-- Alert -->
          <a href="#" onclick="alert('Are you sure you want to delete the comment? Click [OK] to confirm:')">
            <!-- button to delete the comment -->
            <%= button_to "Delete", delete_comment_path(article_id: @article.id, id: comment.id), method: :delete, class: "btn btn-danger btn-sm ms-3" %>
          </a>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

<!-- Add Comments -->
<!-- if show_delete is false, display the add comment section -->
<% if !@show_delete %>
  <div>
    <h5 class="mb-3">Add a comment</h5>
    <!-- Form for creating a new comment associated with the current article -->
    <%= form_with model: [@article, @article.comments.build], class: "d-flex flex-column gap-3" do |f| %>
      <div>
        <!-- Comment field -->
        <%= f.text_area :body, class: "form-control", rows: 4, placeholder: "Enter Comment", required: true %>
      </div>
      <!-- Submit button -->
      <%= f.submit "Submit", class: "btn btn-primary align-self-start" %>
    <% end %>
  </div>
<% end %>