config/routes.rb
Rails.application.routes.draw do
  # Routes for Articles
  get "articles/index", to: "articles#index", as: "index_articles"
  get "articles/search", to: "articles#search", as: "search_articles"
  get "articles/list", to: "articles#list", as: "list_articles"
  get "articles/new", to: "articles#new", as: "new_article"
  post "articles/create", to: "articles#create", as: "create_article"
  patch "articles/update/:id", to: "articles#update", as: "update_article"
  get "articles/show/:id", to: "articles#show", as: "show_article"
  get "articles/edit/:id", to: "articles#edit", as: "edit_article"
  delete "articles/delete/:id", to: "articles#destroy", as: "delete_article"

  # Routes for comments under a specific article
  post "articles/:article_id/comments", to: "comments#create", as: "article_comments"
  delete "articles/:article_id/comments/:id", to: "comments#destroy", as: "delete_comment"

  # Routes for Categories
  get "categories/list", to: "categories#list", as: "list_categories"
  get "categories/new", to: "categories#new", as: "new_category"
  post "categories/create", to: "categories#create", as: "create_category"
  patch "categories/update/:id", to: "categories#update", as: "update_category"
  get "categories/show/:id", to: "categories#show", as: "show_category"
  get "categories/show_delete/:id", to: "categories#show_delete", as: "show_delete_category"
  delete "categories/delete/:id", to: "categories#destroy", as: "delete_category"

  # Routes for Admins
  get "admins/index", to: "admins#index", as: "index_admins"
  patch "admins/hide_unhide/:id", to: "articles#hide_unhide", as: "hide_unhide"
  get "admins/show_delete/:id", to: "articles#show_delete", as: "show_delete"
  get "admins/hidden", to: "articles#show_hidden", as: "hidden_articles"
  get "admins/index/:id", to: "admins#index", as: "index_admins_id"
  get "admins/register", to: "admins#register_form", as: "show_register"
  post "admins/register", to: "admins#register", as: "register"
  get "admins/login", to: "admins#login_form", as: "show_login"
  post "admins/login", to: "admins#login", as: "login"
  delete "logout", to: "admins#logout", as: "logout"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # Default root
  root "articles#index"

end

app/models/category.rb
class Category < ApplicationRecord
  #Set up the relationship with Article model and add scope to filter articles and sort them by the created date
  has_many :articles, -> { where(is_hidden: false).order(created_at: :desc) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # List all categories (Categories page/list.html.erb)
  def list
    # Check if an admin is logged in
    if session[:admin_id]
      # Retrieve all categories in alphabetical order except "Unknown (id: 13)"
      @categories = Category.where.not(id: 13).order(name: :asc)
    else
      # Retrieve all categories in alphabetical order
      @categories = Category.order(name: :asc)
    end
  end

  # Show all articles associated with the category selected by user
  def show
    # Find the selected category by its ID
    @category = Category.find(params[:id])
    # Retrieve all articles within the category
    @articles = @category.articles.order(created_at: :desc)
  end

  # Render the form for creating a new category
  def new
    # Initialise a new Category object
    @category = Category.new
  end

  # Create a new category and save it to the database
  def create
    # Initialise a new category with the parameters submitted via the form (using strong parameters)
    @category = Category.new(category_params)
    # # Attempt to save the category and check if it was successful
    if @category.save
      # Redirect the user to the categories page (list.html.erb)
      redirect_to list_categories_path
      # Store a success message to be displayed on the page
      flash[:category_notice] = "Category created successfully!"
    else
      # Re-render the new category form
      render :new
      # Store an error message to be displayed above the new category form
      flash.now[:alert] = "Category not created. #{@category.errors.full_messages.to_sentence}"
    end
  end

  # Update an existing category
  def update
    # Find the selected category by its ID
    @category = Category.find(params[:id])
    # Check if the category is successfully updated
    if @category.update(category_params)
      # Redirect the user to the categories page (list.html.erb)
      redirect_to list_categories_path
      # Store a success message to be displayed on the page
      flash[:category_notice] = "Category updated successfully!"
    else
      # Re-render the category page
      render list_categories_path
      # Store an error message to be displayed on the page
      flash.now[:alert] = "Category not updated. #{@category.errors.full_messages.to_sentence}"
    end
  end

  # Show the warning message for the category deletion
  def show_delete
    # Retrieve a category based on the ID passed in the params
    @category = Category.find(params[:id])
    # Retrieve all articles in order by created date
    @articles = @category.articles.order(created_at: :desc)
    render :show
  end

  # Delete a category from the database
  def destroy
    # Retrieve a category based on the ID passed in the params
    @category = Category.find(params[:id])
    # Update all articles within the category and assign them to the "Unknown"(id = 13)
    @category.articles.update_all(category_id: 13)
    # Delete the category
    @category.destroy
    # Redirect the user to the categories page (list.html.erb)
    redirect_to list_categories_path
    # Store a success message to be displayed on the page
    flash[:category_notice] = "Category deleted successfully!"

  end

  # Reusable component ---------------------------------------------------------------------
  private # Restrict access to the following method for security
  # Strong parameters for category
  def category_params
    params.require(:category).permit(:name)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/list.html.erb
<!------------ Categories page for all users ------------>
<!-- If there are no categories in the @categories array, display a message -->
<% if @categories.blank? %>
  <p>No categories found.</p>
<% else %>
  <!-- If a category was just updated by admin, display a success/error message -->
  <% if flash[:category_notice] && session[:admin_id] %>
    <p class="text-success fw-bold"><%= flash[:category_notice] %></p>
  <% elsif flash[:alert] %>
    <p class="text-danger fw-bold"><%= flash[:alert] %></p>
  <% end %>
  <!-- Display the category list-->
  <div class="d-flex justify-content-between align-items-center">
    <!-- Select the appropriate heading by checking if an admin session is on -->
    <h2><%= session[:admin_id] ? "Manage Categories" : "Categories" %></h2>
    <!-- New Category button linked to new category form -->
    <%= link_to "Add New Category", new_category_path, type: "button", class: "btn btn-outline-primary" %>
  </div>
  <!-- horizontal line -->
  <hr/>
  <!-- Display the category list-->
  <ul style="list-style: none; padding: 0; margin: 0;" id="categories">
    <!-- Loop through each category in the @categories array -->
    <% @categories.each do |category| %>
      <li class="mb-3">
        <!-- If an admin is logged in, display the edit/delete form-->
        <% if session[:admin_id] %>
          <div class="d-flex align-items-center">
            <!-- Category edit/delete form -->
            <%= form_with(model: category, url: update_category_path(category), method: :patch, local: true, class: "d-flex align-items-center") do |f| %>
              <div class="me-3 flex-grow-1">
                <!-- Category name (editable) -->
                <%= f.text_field :name, class: "form-control", required: true %>
              </div>
              <!-- Update button -->
              <div class="me-3">
                <%= f.submit "Update", class: "btn btn-primary" %>
              </div>
            <% end %>
            <!-- Delete button linked to show delete view (individual article page) -->
            <%= button_to "Delete", show_delete_category_path(category), method: :get, class: "btn btn-danger" %>
          </div>
        <!-- If an admin is not logged in, simply list categories -->
        <% else %>
          <h5><%= link_to category.name, show_category_path(category), style: "text-decoration: none;" %></h5>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/categories/new.html.erb
<!------------ New Category page for admins ------------>
<h2>Add new category</h2>
<!-- horizontal line -->
<hr/>
<!-- New Category form -->
<%= form_with(model: @category, url: create_category_path, method: :post, local: true) do |f| %>
  <!-- Category Name field -->
  <div class="mb-3">
    <%= f.label :name, "Category Name", class: "col-form-label" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter New Category Name", required: true %>
  </div>
  <!-- Submit button -->
  <div class="mb-3">
    <%= f.submit "Create", class: "btn btn-primary align-self-start" %>
  </div>
<% end %>

<!-- If the data is not saved, display an error message -->
<div class="mb-3">
  <% if flash[:alert] %>
    <p class="text-danger fw-bold"><%= flash[:alert] %></p>
  <% end %>
</div>

<!-- Link to the previous page -->
<div><%= link_to "<< Back", list_categories_path, style: "text-decoration: none;" %></div>

app/views/categories/show.html.erb
<!------------ Individual Category page for all users ------------>
<!-- If an admin is logged in, display delete/cancel buttons with a warning -->
<% if session[:admin_id] %>
  <div class="border border-dark p-3 mb-5">
    <!-- Category to delete -->
    <h2>Category: <%= @category.name %></h2>
    <!-- Warning -->
    <h5>Are you sure you want to delete this category?</h5>
    <p class="mb-3">All articles below will be assigned to "Unknown" category.
      <br>This action cannot be undone.</p>
    <!-- Buttons -->
    <div class="d-flex justify-content-start">
      <!-- button to go back to the previous page -->
      <%= button_to "Cancel", list_categories_path, method: :get, class: "btn btn-success" %>
      <!-- button to delete the category -->
      <%= button_to "Delete", delete_category_path(:id => @category.id), method: :delete, class: "btn btn-danger ms-3" %>
    </div>
  </div>
<% end %>
<!-- Display the heading (category name) -->
<h2><%= @category.name %></h2>
<!-- If there are no articles in the @article array (within the category), display a message -->
<% if @articles.blank? %>
  <p>No articles found in this category.</p>
  <!-- If there are no articles (within the category), display their title, date and part of the content -->
<% else %>
  <!-- Display the article list-->
  <ul style="list-style: none; padding: 0; margin: 30px 0 0;" id="articles">
    <!-- Loop through each article in the @articles array -->
    <% @articles.each do |article| %>
      <li>
        <!-- horizontal line -->
        <hr/>
        <!-- Display the article title as a clickable link to the individual article page -->
        <h5><%= link_to article.title, show_article_path(:id => article.id), style: "text-decoration: none;" %></h5>
        <!-- Date the article was created in an appropriate format -->
        <p><%= article.created_at.strftime("%B %d, %Y %H:%M") %></p>
        <p>
          <!-- First 200 words of the article's content -->
          <%= truncate(article.content, length: 200) %>
          <!-- "Read more" link to the individual article page -->
          <%= link_to " Read more >>", show_article_path(:id => article.id), style: "text-decoration: none;" %>
        </p>
      </li>
    <% end %>
    <hr/>
  </ul>
<% end %>