config/routes.rb
Rails.application.routes.draw do
  # Routes for Articles
  get "articles/index", to: "articles#index", as: "index_articles"
  get "articles/search", to: "articles#search", as: "search_articles"
  get "articles/list", to: "articles#list", as: "list_articles"
  get "articles/new", to: "articles#new", as: "new_article"
  post "articles/create", to: "articles#create", as: "create_article"
  patch "articles/update/:id", to: "articles#update", as: "update_article"
  get "articles/show/:id", to: "articles#show", as: "show_article"
  get "articles/edit/:id", to: "articles#edit", as: "edit_article"
  delete "articles/delete/:id", to: "articles#destroy", as: "delete_article"

  # Routes for comments under a specific article
  post "articles/:article_id/comments", to: "comments#create", as: "article_comments"
  delete "articles/:article_id/comments/:id", to: "comments#destroy", as: "delete_comment"

  # Routes for Categories
  get "categories/list", to: "categories#list", as: "list_categories"
  get "categories/new", to: "categories#new", as: "new_category"
  post "categories/create", to: "categories#create", as: "create_category"
  patch "categories/update/:id", to: "categories#update", as: "update_category"
  get "categories/show/:id", to: "categories#show", as: "show_category"
  get "categories/show_delete/:id", to: "categories#show_delete", as: "show_delete_category"
  delete "categories/delete/:id", to: "categories#destroy", as: "delete_category"

  # Routes for Admins
  get "admins/index", to: "admins#index", as: "index_admins"
  patch "admins/hide_unhide/:id", to: "articles#hide_unhide", as: "hide_unhide"
  get "admins/show_delete/:id", to: "articles#show_delete", as: "show_delete"
  get "admins/hidden", to: "articles#show_hidden", as: "hidden_articles"
  get "admins/index/:id", to: "admins#index", as: "index_admins_id"
  get "admins/register", to: "admins#register_form", as: "show_register"
  post "admins/register", to: "admins#register", as: "register"
  get "admins/login", to: "admins#login_form", as: "show_login"
  post "admins/login", to: "admins#login", as: "login"
  delete "logout", to: "admins#logout", as: "logout"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # Default root
  root "articles#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Assessment3 1511679" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap stylesheet -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Bootstrap JavaScript plugin -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Header/Nav for both admin console and all users -->
    <div class="container-fluid">
      <!-- Check if an admin is logged in -->
      <% if session[:admin_id] %>
        <!-- Page title for Admin console with a link to the Admin Home page-->
        <%= link_to "Admin Console", index_admins_path, class: "navbar-brand" %>
      <% else %>
        <!-- Page title for all users with a link to the Home Page -->
        <%= link_to "News Management App", index_articles_path, class: "navbar-brand" %>
      <% end %>
      <!-- Hamburger menu for smaller screens -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- link group/Nav menu -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <!-- Check if an admin is logged in -->
            <% if session[:admin_id] %>
              <!-- Admin Home link (list of visible articles) -->
              <%= link_to "Admin Home", index_admins_path, class: "nav-link" %>
            <% else %>
              <!-- All users Home link (list of the recent articles) -->
              <%= link_to "Home", index_articles_path, class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item">
            <!-- Check if an admin is logged in -->
            <% if session[:admin_id] %>
              <!-- Admin Hidden Articles link (list of hidden articles) -->
              <%= link_to "Hidden Articles", hidden_articles_path, class: "nav-link" %>
            <% else %>
              <!-- All users News page link (list of categories and associated articles -->
              <%= link_to "News", list_articles_path, class: "nav-link" %>
            <% end %>
          </li>
          <li class="nav-item">
            <!-- Categories page link -->
            <%= link_to "Categories", list_categories_path, class: "nav-link" %>
          </li>
        </ul>
        <!-- Search form for articles by keyword -->
        <div class="col-lg-7">
          <%= form_tag search_articles_path, method: :get, class: "d-flex w-80 me-2" do %>
            <%= text_field_tag :search, params[:search], class: "form-control me-2 flex-grow-1", placeholder: "Search for articles by keywords" %>
            <%= submit_tag "Search", class: "btn btn-outline-primary" %>
          <% end %>
        </div>
        <!-- Login/Logout links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <!-- Check if an admin is logged in -->
            <% if session[:admin_id] %>
              <!-- Button to logout -->
              <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-dark" %>
            <% else %>
              <!-- Button to login -->
              <%= link_to "Login", show_login_path, type: "button", class: "btn btn-dark" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
  <!-- This is where the content of each page will be rendered -->
  <div style="width: 90%; margin: 30px auto 100px;" data-turbo="false">
    <%= yield %>
  </div>
  </body>
</html>